### ISSUE TITLE
Two rings of regeneration doesn't work

### ISSUE THREAD

**Issue by RedBeast1959** [Samlegamer/PotionRingReforged#10]
1.19.2 Forge 43.02
potionring-1.19.2-1.0.jar

When equip two rings of regeneration, it shows regeneration 2 applied to player.
But health doesn't heal over time. Just equipping one ring of regeneration works though.
Same problem happens in 1.18.2 version(potionring-1.18.2-1.1.jar).

**Comment by Samlegamer** [comment]
fixed in potionring-1.19.2-1.1

**Comment by Samlegamer** [comment]
This bug is also present on the Fabric version

**Comment by Samlegamer** [comment]
fixed
