### ISSUE TITLE
Ticking Player/Entity Crash

### ISSUE THREAD

**Issue by operamaniac** [Samlegamer/PotionRingReforged#12]
Minecraft Version : 1.19.2
Mod Version : 1.19.2.1.0

Happened when trying to put Ring of Thinning and Widening on Trinket slot. Can't join world because it keep crashing.

Crash log :
https://bytebin.lucko.me/FVCyTKhhfO

Crash log with isolated mod (PRR, Fabric API, Trinket)
https://mclo.gs/jMwsfeI

**Comment by operamaniac** [comment]
So I was tinkering around with the Jar file and it seems the ring mentioned haven't implemented on the current version, I assume? There was no recipe too, I found the item on REI. Is there a way to not register them as an item?

**Comment by Samlegamer** [comment]
Did you have the Size Shifting Potions mod installed, it is a required mod for these rings, it does not appear in the creative tabs ?

**Comment by operamaniac** [comment]
Ah. I haven't installed the Size Shifting mod. I haven't look at the creative tab since I use REI.

I installed it from Prism Launcher mod downloader and it doesn't give any warning about optional dependency.

Just checked Curseforge and there's no mention of Size Shifting mod in the description. Only in the file section. I think you should mention the optional dependency too on the description.
