### ISSUE TITLE
[Bug] Discontinuous effects / Change the regive time

### ISSUE THREAD

**Issue by GoldenTotem** [Samlegamer/PotionRingReforged#15]
Minecraft: 1.16.5  Forge: 36.2.35 Mod: 1.4

If you use the ring of speed, your field of view will decrease and restore immediately. Because potion rings regive effects when effects time come to 0. It may cause effects not always activated, but a little time unactivated at the moment of regiving effects.

**Comment by Samlegamer** [comment]
fixed in 1.16.5-1.7
