### ISSUE TITLE
[Bug] Potion rings obtained with /give command may crash the game

### ISSUE THREAD

**Issue by GoldenTotem** [Samlegamer/PotionRingReforged#16]
Minecraft: 1.16.5 Forge: 36.2.35 Mod: 1.4
Ring of glowing , shrinking etc. will make game crash.

**Comment by Samlegamer** [comment]
Cette anneaux est volontairement caché car il est une compatibilité pour SizeShifting, le crash devrait cessé en l'installant : https://legacy.curseforge.com/minecraft/mc-mods/size-shifting-potions

**Comment by Samlegamer** [comment]
This ring is deliberately hidden because it's a SizeShifting compatibility, so the crash should stop when you install it: https://legacy.curseforge.com/minecraft/mc-mods/size-shifting-potions

**Comment by GoldenTotem** [comment]
> This ring is deliberately hidden because it's a SizeShifting compatibility, so the crash should stop when you install it: https://legacy.curseforge.com/minecraft/mc-mods/size-shifting-potions

I know that.
But those rings will make the game crash when you enter a world. Re-joining world cause re-crash. It means if you use those rings, the world will be permanently broken. It is a very serious bug.
I hope that those unavailable rings will not be registered if the compatible mod is not installed. Otherwise this bug is too fatal.

**Comment by Samlegamer** [comment]
What you need to do to stop the crash:

1) Install SizeShifting
2) Launch your world
3) Remove the compat rings (ring of growing, shrinking, widening, thinning) present on the player then destroy them either by despawn or with lava.
4) Close your world and Minecraft, then remove the previously added mod (SizeShifting)!

Your world should be up and running again without a hitch.

**Comment by Samlegamer** [comment]
I hadn't seen that Forge version 1.16.5 had been removed, so I've released a new update to correct this: https://legacy.curseforge.com/minecraft/mc-mods/potion-ring-reforged/files/4649479
