### ISSUE TITLE
the Curios ring slot is not appearing with this mod

### ISSUE THREAD

**Issue by ghost** [Samlegamer/PotionRingReforged#2]
I have tested this with a completely clean installation Forge - 36.2.9 Mod verison 1.16.5-1.1 and curios version 1.16.5-4.0.5.3
No ring slots are generated, no other slots either. No other mods installed :/

**Comment by Samlegamer** [comment]
Hello I also have the same problem but it comes from curios and not from me.
I have the case with my modpack where with some mod it works but if I have only 2 mods (this one and Curios) it does not work.
I even tried with Curios alone without any other mod and the interface was still not displayed :/
