### ISSUE TITLE
Potion ring crash 

### ISSUE THREAD

**Issue by ghost** [Samlegamer/PotionRingReforged#4]
[Crash due to equipping Potion ring.txt](https://github.com/Samlegamer/PotionRingReforged/files/7929156/Crash.due.to.equipping.Potion.ring.txt)

Issue came forth when attempting to equip a potion ring in a curio ring slot

As a temporary solution, I simply turned off the potion rings mod

**Comment by Samlegamer** [comment]
Hello, version 1.2 of this mod requires the latest version of curios (beta)

https://www.curseforge.com/minecraft/mc-mods/curios/files/3613039
